### PR TITLE
dev/new-apis

### PR DESCRIPTION
**Pull request by mathstuf**
Based on top of SDL-2.0.x and gates things behind the version mechanisms.

### CODE REVIEW

**Comment by aldacron** [comment]
This is great, Ben, thanks! The SDL-2.0.x branch is exactly the place for it. I would have rejected it otherwise. That's going to be merged into master eventually. Can you do me a favor and squash the commits? I'd like them condensed down before I merge them.

**Comment by mathstuf** [comment]
Probably easier to do a review of the individual commits; I can squash if you're fine with the changes.

**Comment by aldacron** [comment]
I was thinking it would be easier to review them if they're squashed, but I suppose it doesn't matter. I'll set aside an hour this weekend to dig into this and all the other stuff I'm falling behind on here. Thanks!

**Comment by aldacron** [comment]
Sorry it took so long. I've merged everything. If you're using 2.0.4 right now, you'll want to specify it in a SharedLibVersion. In order to avoid breaking existing apps, I've explicitly set 2.0.3 to load by default. Once 2.0.4 is released, I'll remove that and 2.0.4 will become the default.

Thanks!

**Pull request merged**
