### PR TITLE
Make anonymous enums into typed enums

### PR DESCRIPTION
**Pull request by UplinkCoder**
I have converted most enums into typed enums while retaining the anonymous enums via a clever parameterized enum.

### CODE REVIEW

**Comment by mdparker** [comment]
I don't have an objection to doing this in theory, but  I'd rather apply the template to the upcoming DerelictUtil 3.0 and convert all the alpha release packages to use it instead of just leaving it in DerelictSDL.

I'd just like to know, is there an existing problem with the current approach? I understand the benefit of typed enums, of course, but is it solving an actual problem you've encountered or is this just more of a "it's nice to have" thing?

**Comment by pineapplemachine** [comment]
I agree that this would be a good change to make. And while I can't speak for Stefan but I haven't personally encountered any problems because of it. I think that holding off until DerelictUtil 3.0 would be acceptable.

**Comment by UplinkCoder** [comment]
It's just the convenience of having `enumType.to!string` say something meaningfull rather then  128

**Comment by mdparker** [comment]
OK, I've added the template to derelict.util.system as 'MakeEnum' and tagged a 3.0.0-alpha.2 release for derelict-util.

I've also tagged a 3.0.0-alpha.3 release of derelict-sdl2 with most of the enum declarations updated to use the new template. I haven't had a chance to test it out on a real project yet. There may be some functions declared to use e.g. Uint32 that will need to be updated to the enum type. At some point, I'll update the less-obvious enums to use it as well.

Thanks!

**Pull request closed without merging**
